=== AMWA-TV/is-10/v1.1-dev/schemas/resolved/register_client_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Register Client Response",
  "description": "Object defining successful client registration",
  "type": "object",
  "properties": {
    "client_id": {
      "description": "OAuth 2.0 client identifier string",
      "type": "string"
    },
    "client_secret": {
      "description": "OAuth 2.0 client secret string",
      "type": "string"
    },
    "client_id_issued_at": {
      "description": "UTC time at which the client identifier was issued",
      "type": "number"
    },
    "client_secret_expires_at": {
      "description": "Time at which the client secret will expire or 0 if it will not expire",
      "type": "number"
    },
    "redirect_uris": {
      "description": "Array of redirection URI strings for use in redirect-based flows such as the authorization code and implicit flows",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "token_endpoint_auth_method": {
      "description": "String indicator of the requested authentication method for the token endpoint",
      "type": "string",
      "default": "client_secret_basic"
    },
    "grant_types": {
      "description": "Array of OAuth 2.0 grant type strings that the client can use at the token endpoint",
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": [
        "authorization_code"
      ]
    },
    "response_types": {
      "description": "Array of the OAuth 2.0 response type strings that the client can use at the authorization endpoint",
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": [
        "code"
      ]
    },
    "client_name": {
      "description": "Human-readable string name of the client to be presented to the end-user during authorization",
      "type": "string"
    },
    "client_uri": {
      "description": "URL string of a web page providing information about the client",
      "type": "string"
    },
    "logo_uri": {
      "description": "URL string that references a logo for the client",
      "type": "string"
    },
    "scope": {
      "description": "String containing a space-separated list of scope values",
      "type": "string"
    },
    "contacts": {
      "description": "Array of strings representing ways to contact people responsible for this client, typically email addresses",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tos_uri": {
      "description": "URL string that points to a human-readable terms of service document for the client",
      "type": "string"
    },
    "policy_uri": {
      "description": "URL string that points to a human-readable privacy policy document",
      "type": "string"
    },
    "jwks_uri": {
      "description": "URL string referencing the client's JSON Web Key (JWK) Set document, which contains the client's public keys",
      "type": "string"
    },
    "jwks": {
      "description": "Client's JSON Web Key Set document value, which contains the client's public keys",
      "type": "object",
      "allOf": [
        {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "title": "JSON Web Key Set",
          "description": "JSON Web Key Set to validate JSON Web Token",
          "type": "object",
          "properties": {
            "keys": {
              "description": "The value of the 'keys' parameter is an array of JWK values. By default, the order of the JWK values within the array does not imply an order of preference among them, although applications of JWK Sets can choose to assign a meaning to the order for their purposes, if desired.",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "kty": {
                    "type": "string"
                  },
                  "use": {
                    "type": "string"
                  },
                  "key_ops": {
                    "type": "string"
                  },
                  "alg": {
                    "type": "string"
                  },
                  "kid": {
                    "type": "string"
                  },
                  "x5u": {
                    "type": "string",
                    "format": "uri"
                  },
                  "x5c": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "x5t": {
                    "type": "string"
                  },
                  "x5t#S256": {
                    "type": "string"
                  }
                },
                "required": [
                  "kty"
                ]
              }
            }
          },
          "required": [
            "keys"
          ]
        }
      ]
    },
    "software_id": {
      "description": "A unique identifier string (e.g. a UUID) assigned by the client developer or software publisher",
      "type": "string"
    },
    "software_version": {
      "description": "A version identifier string for the client software identified by 'software_id'",
      "type": "string"
    }
  },
  "required": [
    "client_id"
  ]
}

=== AMWA-TV/is-10/examples/register-authorization-code-grant-client-post-201.json
{
  "client_id": "s6BhdRkqt3",
  "client_id_issued_at": 2893256800,
  "client_secret": "cf136dc3c1fc93f31185e5885805d",
  "client_secret_expires_at": 2893276800,
  "redirect_uris": [
    "https://client.example.org/callback",
    "https://client.example.org/callback2"
  ],
  "scope": "query connection",
  "token_endpoint_auth_method": "client_secret_basic"
}
